# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:02:04+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class Availability(BaseModel):
    advertiserId: Optional[str] = Field(None, description='DS advertiser ID.')
    agencyId: Optional[str] = Field(None, description='DS agency ID.')
    availabilityTimestamp: Optional[str] = Field(
        None,
        description='The time by which all conversions have been uploaded, in epoch millis UTC.',
    )
    customerId: Optional[str] = Field(
        None,
        description='Customer ID of a client account in the new Search Ads 360 experience.',
    )
    segmentationId: Optional[str] = Field(
        None,
        description='The numeric segmentation identifier (for example, DoubleClick Search Floodlight activity ID).',
    )
    segmentationName: Optional[str] = Field(
        None,
        description='The friendly segmentation identifier (for example, DoubleClick Search Floodlight activity name).',
    )
    segmentationType: Optional[str] = Field(
        None,
        description='The segmentation type that this availability is for (its default value is `FLOODLIGHT`).',
    )


class CustomDimension(BaseModel):
    name: Optional[str] = Field(None, description='Custom dimension name.')
    value: Optional[str] = Field(None, description='Custom dimension value.')


class CustomMetric(BaseModel):
    name: Optional[str] = Field(None, description='Custom metric name.')
    value: Optional[float] = Field(None, description='Custom metric numeric value.')


class IdMappingFile(BaseModel):
    pass


class File(BaseModel):
    byteCount: Optional[str] = Field(
        None, description='The size of this report file in bytes.'
    )
    url: Optional[str] = Field(
        None, description='Use this url to download the report file.'
    )


class ReportApiColumnSpec(BaseModel):
    columnName: Optional[str] = Field(
        None,
        description='Name of a DoubleClick Search column to include in the report.',
    )
    customDimensionName: Optional[str] = Field(
        None,
        description='Segments a report by a custom dimension. The report must be scoped to an advertiser or lower, and the custom dimension must already be set up in DoubleClick Search. The custom dimension name, which appears in DoubleClick Search, is case sensitive.\\ If used in a conversion report, returns the value of the specified custom dimension for the given conversion, if set. This column does not segment the conversion report.',
    )
    customMetricName: Optional[str] = Field(
        None,
        description='Name of a custom metric to include in the report. The report must be scoped to an advertiser or lower, and the custom metric must already be set up in DoubleClick Search. The custom metric name, which appears in DoubleClick Search, is case sensitive.',
    )
    endDate: Optional[str] = Field(
        None,
        description='Inclusive day in YYYY-MM-DD format. When provided, this overrides the overall time range of the report for this column only. Must be provided together with `startDate`.',
    )
    groupByColumn: Optional[bool] = Field(
        None,
        description='Synchronous report only. Set to `true` to group by this column. Defaults to `false`.',
    )
    headerText: Optional[str] = Field(
        None,
        description='Text used to identify this column in the report output; defaults to `columnName` or `savedColumnName` when not specified. This can be used to prevent collisions between DoubleClick Search columns and saved columns with the same name.',
    )
    platformSource: Optional[str] = Field(
        None,
        description='The platform that is used to provide data for the custom dimension. Acceptable values are "floodlight".',
    )
    productReportPerspective: Optional[str] = Field(
        None,
        description='Returns metrics only for a specific type of product activity. Accepted values are: - "`sold`": returns metrics only for products that were sold - "`advertised`": returns metrics only for products that were advertised in a Shopping campaign, and that might or might not have been sold ',
    )
    savedColumnName: Optional[str] = Field(
        None,
        description='Name of a saved column to include in the report. The report must be scoped at advertiser or lower, and this saved column must already be created in the DoubleClick Search UI.',
    )
    startDate: Optional[str] = Field(
        None,
        description='Inclusive date in YYYY-MM-DD format. When provided, this overrides the overall time range of the report for this column only. Must be provided together with `endDate`.',
    )


class Filter(BaseModel):
    column: Optional[ReportApiColumnSpec] = Field(
        None,
        description='Column to perform the filter on. This can be a DoubleClick Search column or a saved column.',
    )
    operator: Optional[str] = Field(
        None,
        description='Operator to use in the filter. See the filter reference for a list of available operators.',
    )
    values: Optional[List] = Field(
        None,
        description='A list of values to filter the column value against.\\ The maximum number of filter values per request is 300.',
    )


class OrderByItem(BaseModel):
    column: Optional[ReportApiColumnSpec] = Field(
        None,
        description='Column to perform the sort on. This can be a DoubleClick Search-defined column or a saved column.',
    )
    sortOrder: Optional[str] = Field(
        None,
        description='The sort direction, which is either `ascending` or `descending`.',
    )


class ReportScope(BaseModel):
    adGroupId: Optional[str] = Field(None, description='DS ad group ID.')
    adId: Optional[str] = Field(None, description='DS ad ID.')
    advertiserId: Optional[str] = Field(None, description='DS advertiser ID.')
    agencyId: Optional[str] = Field(None, description='DS agency ID.')
    campaignId: Optional[str] = Field(None, description='DS campaign ID.')
    engineAccountId: Optional[str] = Field(None, description='DS engine account ID.')
    keywordId: Optional[str] = Field(None, description='DS keyword ID.')


class TimeRange(BaseModel):
    changedAttributesSinceTimestamp: Optional[str] = Field(
        None,
        description='Inclusive UTC timestamp in RFC format, e.g., `2013-07-16T10:16:23.555Z`. See additional references on how changed attribute reports work.',
    )
    changedMetricsSinceTimestamp: Optional[str] = Field(
        None,
        description='Inclusive UTC timestamp in RFC format, e.g., `2013-07-16T10:16:23.555Z`. See additional references on how changed metrics reports work.',
    )
    endDate: Optional[str] = Field(
        None, description='Inclusive date in YYYY-MM-DD format.'
    )
    startDate: Optional[str] = Field(
        None, description='Inclusive date in YYYY-MM-DD format.'
    )


class ReportRequest(BaseModel):
    columns: Optional[List[ReportApiColumnSpec]] = Field(
        None,
        description='The columns to include in the report. This includes both DoubleClick Search columns and saved columns. For DoubleClick Search columns, only the `columnName` parameter is required. For saved columns only the `savedColumnName` parameter is required. Both `columnName` and `savedColumnName` cannot be set in the same stanza.\\ The maximum number of columns per request is 300.',
    )
    downloadFormat: Optional[str] = Field(
        None,
        description='Format that the report should be returned in. Currently `csv` or `tsv` is supported.',
    )
    filters: Optional[List[Filter]] = Field(
        None,
        description='A list of filters to be applied to the report.\\ The maximum number of filters per request is 300.',
    )
    includeDeletedEntities: Optional[bool] = Field(
        None,
        description='Determines if removed entities should be included in the report. Defaults to `false`. Deprecated, please use `includeRemovedEntities` instead.',
    )
    includeRemovedEntities: Optional[bool] = Field(
        None,
        description='Determines if removed entities should be included in the report. Defaults to `false`.',
    )
    maxRowsPerFile: Optional[int] = Field(
        None,
        description='Asynchronous report only. The maximum number of rows per report file. A large report is split into many files based on this field. Acceptable values are `1000000` to `100000000`, inclusive.',
    )
    orderBy: Optional[List[OrderByItem]] = Field(
        None,
        description='Synchronous report only. A list of columns and directions defining sorting to be performed on the report rows.\\ The maximum number of orderings per request is 300.',
    )
    reportScope: Optional[ReportScope] = Field(
        None,
        description='The reportScope is a set of IDs that are used to determine which subset of entities will be returned in the report. The full lineage of IDs from the lowest scoped level desired up through agency is required.',
    )
    reportType: Optional[str] = Field(
        None,
        description='Determines the type of rows that are returned in the report. For example, if you specify `reportType: keyword`, each row in the report will contain data about a keyword. See the [Types of Reports](/search-ads/v2/report-types/) reference for the columns that are available for each type.',
    )
    rowCount: Optional[int] = Field(
        None,
        description='Synchronous report only. The maximum number of rows to return; additional rows are dropped. Acceptable values are `0` to `10000`, inclusive. Defaults to `10000`.',
    )
    startRow: Optional[int] = Field(
        None,
        description='Synchronous report only. Zero-based index of the first row to return. Acceptable values are `0` to `50000`, inclusive. Defaults to `0`.',
    )
    statisticsCurrency: Optional[str] = Field(
        None,
        description='Specifies the currency in which monetary will be returned. Possible values are: `usd`, `agency` (valid if the report is scoped to agency or lower), `advertiser` (valid if the report is scoped to * advertiser or lower), or `account` (valid if the report is scoped to engine account or lower).',
    )
    timeRange: Optional[TimeRange] = Field(
        None,
        description='If metrics are requested in a report, this argument will be used to restrict the metrics to a specific time range.',
    )
    verifySingleTimeZone: Optional[bool] = Field(
        None,
        description='If `true`, the report would only be created if all the requested stat data are sourced from a single timezone. Defaults to `false`.',
    )


class ReportRow(RootModel[Optional[Dict[str, Any]]]):
    root: Optional[Dict[str, Any]] = Field(
        None,
        description='Indicates the columns that are represented in this row. That is, each key corresponds to a column with a non-empty cell in this row.',
    )


class SavedColumn(BaseModel):
    kind: Optional[str] = Field(
        None,
        description='Identifies this as a SavedColumn resource. Value: the fixed string doubleclicksearch#savedColumn.',
    )
    savedColumnName: Optional[str] = Field(
        None, description='The name of the saved column.'
    )
    type: Optional[str] = Field(
        None, description='The type of data this saved column will produce.'
    )


class SavedColumnList(BaseModel):
    items: Optional[List[SavedColumn]] = Field(
        None, description='The saved columns being requested.'
    )
    kind: Optional[str] = Field(
        None,
        description='Identifies this as a SavedColumnList resource. Value: the fixed string doubleclicksearch#savedColumnList.',
    )


class UpdateAvailabilityRequest(BaseModel):
    availabilities: Optional[List[Availability]] = Field(
        None, description='The availabilities being requested.'
    )


class UpdateAvailabilityResponse(BaseModel):
    availabilities: Optional[List[Availability]] = Field(
        None, description='The availabilities being returned.'
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class Conversion(BaseModel):
    adGroupId: Optional[str] = Field(None, description='DS ad group ID.')
    adId: Optional[str] = Field(None, description='DS ad ID.')
    advertiserId: Optional[str] = Field(None, description='DS advertiser ID.')
    agencyId: Optional[str] = Field(None, description='DS agency ID.')
    attributionModel: Optional[str] = Field(
        None,
        description='Available to advertisers only after contacting DoubleClick Search customer support.',
    )
    campaignId: Optional[str] = Field(None, description='DS campaign ID.')
    channel: Optional[str] = Field(
        None,
        description='Sales channel for the product. Acceptable values are: - "`local`": a physical store - "`online`": an online store ',
    )
    clickId: Optional[str] = Field(None, description='DS click ID for the conversion.')
    conversionId: Optional[str] = Field(
        None,
        description="For offline conversions, advertisers provide this ID. Advertisers can specify any ID that is meaningful to them. Each conversion in a request must specify a unique ID, and the combination of ID and timestamp must be unique amongst all conversions within the advertiser. For online conversions, DS copies the `dsConversionId` or `floodlightOrderId` into this property depending on the advertiser's Floodlight instructions.",
    )
    conversionModifiedTimestamp: Optional[str] = Field(
        None,
        description='The time at which the conversion was last modified, in epoch millis UTC.',
    )
    conversionTimestamp: Optional[str] = Field(
        None,
        description='The time at which the conversion took place, in epoch millis UTC.',
    )
    countMillis: Optional[str] = Field(
        None,
        description='Available to advertisers only after contacting DoubleClick Search customer support.',
    )
    criterionId: Optional[str] = Field(None, description='DS criterion (keyword) ID.')
    currencyCode: Optional[str] = Field(
        None,
        description="The currency code for the conversion's revenue. Should be in ISO 4217 alphabetic (3-char) format.",
    )
    customDimension: Optional[List[CustomDimension]] = Field(
        None,
        description='Custom dimensions for the conversion, which can be used to filter data in a report.',
    )
    customMetric: Optional[List[CustomMetric]] = Field(
        None, description='Custom metrics for the conversion.'
    )
    customerId: Optional[str] = Field(
        None,
        description='Customer ID of a client account in the new Search Ads 360 experience.',
    )
    deviceType: Optional[str] = Field(
        None, description='The type of device on which the conversion occurred.'
    )
    dsConversionId: Optional[str] = Field(
        None, description='ID that DoubleClick Search generates for each conversion.'
    )
    engineAccountId: Optional[str] = Field(None, description='DS engine account ID.')
    floodlightOrderId: Optional[str] = Field(
        None,
        description='The Floodlight order ID provided by the advertiser for the conversion.',
    )
    inventoryAccountId: Optional[str] = Field(
        None,
        description='ID that DS generates and uses to uniquely identify the inventory account that contains the product.',
    )
    productCountry: Optional[str] = Field(
        None,
        description='The country registered for the Merchant Center feed that contains the product. Use an ISO 3166 code to specify a country.',
    )
    productGroupId: Optional[str] = Field(None, description='DS product group ID.')
    productId: Optional[str] = Field(None, description='The product ID (SKU).')
    productLanguage: Optional[str] = Field(
        None,
        description='The language registered for the Merchant Center feed that contains the product. Use an ISO 639 code to specify a language.',
    )
    quantityMillis: Optional[str] = Field(
        None, description='The quantity of this conversion, in millis.'
    )
    revenueMicros: Optional[str] = Field(
        None,
        description='The revenue amount of this `TRANSACTION` conversion, in micros (value multiplied by 1000000, no decimal). For example, to specify a revenue value of "10" enter "10000000" (10 million) in your request.',
    )
    segmentationId: Optional[str] = Field(
        None,
        description='The numeric segmentation identifier (for example, DoubleClick Search Floodlight activity ID).',
    )
    segmentationName: Optional[str] = Field(
        None,
        description='The friendly segmentation identifier (for example, DoubleClick Search Floodlight activity name).',
    )
    segmentationType: Optional[str] = Field(
        None,
        description='The segmentation type of this conversion (for example, `FLOODLIGHT`).',
    )
    state: Optional[str] = Field(
        None,
        description='The state of the conversion, that is, either `ACTIVE` or `REMOVED`. Note: state DELETED is deprecated.',
    )
    storeId: Optional[str] = Field(
        None,
        description='The ID of the local store for which the product was advertised. Applicable only when the channel is "`local`".',
    )
    type: Optional[str] = Field(
        None,
        description='The type of the conversion, that is, either `ACTION` or `TRANSACTION`. An `ACTION` conversion is an action by the user that has no monetarily quantifiable value, while a `TRANSACTION` conversion is an action that does have a monetarily quantifiable value. Examples are email list signups (`ACTION`) versus ecommerce purchases (`TRANSACTION`).',
    )


class ConversionList(BaseModel):
    conversion: Optional[List[Conversion]] = Field(
        None, description='The conversions being requested.'
    )
    kind: Optional[str] = Field(
        None,
        description='Identifies this as a ConversionList resource. Value: the fixed string doubleclicksearch#conversionList.',
    )


class Report(BaseModel):
    files: Optional[List[File]] = Field(
        None,
        description='Asynchronous report only. Contains a list of generated report files once the report has successfully completed.',
    )
    id: Optional[str] = Field(
        None, description='Asynchronous report only. Id of the report.'
    )
    isReportReady: Optional[bool] = Field(
        None,
        description='Asynchronous report only. True if and only if the report has completed successfully and the report files are ready to be downloaded.',
    )
    kind: Optional[str] = Field(
        None,
        description='Identifies this as a Report resource. Value: the fixed string `doubleclicksearch#report`.',
    )
    request: Optional[ReportRequest] = Field(
        None,
        description='The request that created the report. Optional fields not specified in the original request are filled with default values.',
    )
    rowCount: Optional[int] = Field(
        None,
        description='The number of report rows generated by the report, not including headers.',
    )
    rows: Optional[List[ReportRow]] = Field(
        None, description='Synchronous report only. Generated report rows.'
    )
    statisticsCurrencyCode: Optional[str] = Field(
        None,
        description='The currency code of all monetary values produced in the report, including values that are set by users (e.g., keyword bid settings) and metrics (e.g., cost and revenue). The currency code of a report is determined by the `statisticsCurrency` field of the report request.',
    )
    statisticsTimeZone: Optional[str] = Field(
        None,
        description='If all statistics of the report are sourced from the same time zone, this would be it. Otherwise the field is unset.',
    )
